# credentials.yaml

aws:
  access_key_id: "your_access_key_id"
  secret_access_key: "your_secret_access_key"

gcloud:
  service_account_key_path: "path/to/your/service_account_key.json"

database:
  host: "localhost"
  port: 5432
  username: "your_db_username"
  password: "your_db_password"
  database_name: "your_database_name"
